🆙 Update for Node 16 support
ActionsDesk/ghec-invitations-report-action pull request #178
Opened 2023-08-22 08:00 UTC by stoe

- 🔧 Update configs
- ⬆️ Preparwe for Node16 support
- ✅ Update tests
- ♻️ Refactor for Node16 support
- 📦️ Update `dist/`

2023-08-22 08:12 UTC, stoe commented
Next step after merge: Create new release!

2024-09-27 20:01 UTC, gclhub requested changes
@stoe I saw that you already have a PR to a newer nodeJS version in this repo, so I added a couple of suggestions to upgrade to node v20 in response to the prompt from @stebje to upgrade the ActionsDesk repositories.

2024-09-27 20:01 UTC, gclhub commented on action.yml
> +  using: 'node16'
```suggestion
  using: 'node20'
```

2024-09-29 09:51 UTC, stoe commented on package.json
> +    "npm": ">=8"
```suggestion
    "node": ">=20",
    "npm": ">=10"
```

2024-09-30 17:48 UTC, gclhub approved these changes
LGTM :shipit:

2024-10-01 06:15 UTC, merged