v2.0.0
ActionsDesk/ghec-invitations-report-action pull request #18
Opened 2020-11-13 10:22 UTC by stoe

2020-11-17 15:44 UTC, droidpl approved these changes
All looks pretty solid 😄  Just added a minor idea in case you want to add it

2020-11-17 15:44 UTC, droidpl commented on index.js
>        committer: {
Should the committer params be customizable? Otherwise maybe they want to link those to a service account

2020-11-17 16:02 UTC, stoe commented on index.js
>        committer: {
Great idea, wanna start a PR, @droidpl?

2020-11-17 23:10 UTC, froi requested changes

2020-11-18 14:26 UTC, froi approved these changes
Very nice @stoe :shipit:

2020-11-18 15:14 UTC, merged